CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_Z_SHELL=y
CONFIG_MAIN_STACK_SIZE=4096

# --- CONFIG DISPLAY ---
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_DISPLAY_LOG_LEVEL_ERR=y

CONFIG_INPUT=y
CONFIG_LOG=y
CONFIG_SHELL=y

# --- CONFIG LVGL CHUẨN ĐƠN SẮC 1-BIT ---
CONFIG_LVGL=y
CONFIG_LV_COLOR_DEPTH_1=y
CONFIG_LV_Z_BITS_PER_PIXEL=1
CONFIG_LV_Z_VDB_SIZE=64
CONFIG_LV_USE_THEME_DEFAULT=n

CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_FONT_MONTSERRAT_14=y

# --- BẬT STACK MẠNG CỦA ZEPHYR ---
CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_LOG=y
CONFIG_NET_SHELL=y

# --- CẤU HÌNH IPV4 VÀ DHCP ---
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y

# --- BẬT TÍNH NĂNG WI-FI ---
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y

CONFIG_NET_L2_WIFI_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_NET_DHCPV4_SERVER=y
CONFIG_WIFI_SAMPLE_AP_SSID="hello"
CONFIG_WIFI_SAMPLE_SSID="thuy_trang_xinh_dep"
CONFIG_WIFI_SAMPLE_PSK="ffffffff"
CONFIG_WIFI_SAMPLE_AP_NETMASK="255.255.255.0"
CONFIG_WIFI_SAMPLE_AP_IP_ADDRESS="192.168.4.1"

CONFIG_POSIX_API=y
CONFIG_POSIX_C_LANG_SUPPORT_R=y
CONFIG_SNTP=y
CONFIG_NET_CONFIG_CLOCK_SNTP_INIT=y
CONFIG_NET_CONFIG_SNTP_INIT_SERVER="vn.pool.ntp.org"
CONFIG_NET_CONFIG_SNTP_INIT_RESYNC=y

CONFIG_DNS_RESOLVER=y
CONFIG_DNS_SERVER_IP_ADDRESSES=y
CONFIG_DNS_SERVER1="8.8.8.8"
CONFIG_DNS_SERVER2="8.8.4.4"

CONFIG_NET_LOG=y
CONFIG_NET_SOCKETS_SERVICE=y
CONFIG_ZVFS_POLL_MAX=4
CONFIG_NET_CONNECTION_MANAGER=y

CONFIG_STDOUT_CONSOLE=y
# enable to use thread names
CONFIG_THREAD_NAME=y